trigger:
  batch: true
  branches:
    include:
    - dev
  paths:
    exclude:
    - README.md

pr: none

variables:
  agentOS: ubuntu-latest
  docker_repo: skyere/greencity-front
  artifactName: drop

stages:
- stage: Build
  jobs: 
  - job: Build
    pool:
      vmImage: $(agentOS)
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
    
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '.'
    
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: '.'
        customCommand: 'npx ng build --prod --base-href=/GreenCityClient/'

    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub_Skyere'
        repository: '$(docker_repo)'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: |
          dev-$(Build.BuildId)
          latest
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub_Skyere'
        repository: '$(docker_repo)'
        command: 'push'
        tags: |
          dev-$(Build.BuildId)
          latest

    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/greencity-client-chart'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/greencity-client-chart'
    
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: '$(artifactName)'